# Generated by Django 4.0.2 on 2022-02-16 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookId', models.AutoField(primary_key=True, serialize=False)),
                ('bookName', models.CharField(max_length=300)),
                ('authorName', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='BookEntry',
            fields=[
                ('bookEntryId', models.AutoField(primary_key=True, serialize=False)),
                ('bookName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
