# Generated by Django 4.0.2 on 2023-02-22 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookEntry',
        ),
    ]
